// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtvtoowocispdntduphk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0dnRvb3dvY2lzcGRudGR1cGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzODk1NTYsImV4cCI6MjA3MDk2NTU1Nn0.sf_vAb0oVyHRUgqv9HDKJko2fYojP-QrvL89DtbMuIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});